/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { LaborGrounds, LaborGroundsInterface } from "../LaborGrounds";

const _abi = [
  {
    inputs: [],
    name: "CannotClaimNow",
    type: "error",
  },
  {
    inputs: [],
    name: "CsToHigh",
    type: "error",
  },
  {
    inputs: [],
    name: "DevelopmentGroundIsLocked",
    type: "error",
  },
  {
    inputs: [],
    name: "InvalidTokenForThisJob",
    type: "error",
  },
  {
    inputs: [],
    name: "LengthsNotEqual",
    type: "error",
  },
  {
    inputs: [],
    name: "NewOwnerIsZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "NoHandoverRequest",
    type: "error",
  },
  {
    inputs: [],
    name: "NoMoreAnimalsAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "NotYourToken",
    type: "error",
  },
  {
    inputs: [],
    name: "TokenIsStaked",
    type: "error",
  },
  {
    inputs: [],
    name: "Unauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "animalsId",
        type: "uint256",
      },
    ],
    name: "BringInAnimalsToLaborGround",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "ClaimCollectable",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "supplyId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "enum Jobs",
        name: "job",
        type: "uint8",
      },
    ],
    name: "EnterLaborGround",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint8",
        name: "version",
        type: "uint8",
      },
    ],
    name: "Initialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "LeaveLaborGround",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverCanceled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "OwnershipHandoverRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "oldOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "owner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "animalsId",
        type: "uint256",
      },
    ],
    name: "RemoveAnimalsFromLaborGround",
    type: "event",
  },
  {
    inputs: [],
    name: "animals",
    outputs: [
      {
        internalType: "contract IERC1155Upgradeable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_animalsId",
        type: "uint256[]",
      },
    ],
    name: "bringInAnimalsToLaborGround",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
    ],
    name: "claimCollectables",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "completeOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "consumables",
    outputs: [
      {
        internalType: "contract IConsumables",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
      {
        internalType: "uint256[]",
        name: "_supplyId",
        type: "uint256[]",
      },
      {
        internalType: "enum Jobs[]",
        name: "_job",
        type: "uint8[]",
      },
    ],
    name: "enterLaborGround",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "getLaborGroundFeInfo",
    outputs: [
      {
        components: [
          {
            internalType: "uint64",
            name: "timeLeft",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "tokenId",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "animalId",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "supplyId",
            type: "uint64",
          },
        ],
        internalType: "struct LaborGroundFeInfo[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_tokenId",
        type: "uint256",
      },
    ],
    name: "getLaborGroundInfo",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "lockTime",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "supplyId",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "animalId",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "requestId",
            type: "uint256",
          },
          {
            internalType: "enum Jobs",
            name: "job",
            type: "uint8",
          },
        ],
        internalType: "struct LaborGround",
        name: "lg",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "getStakedTokens",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pits",
        type: "address",
      },
      {
        internalType: "address",
        name: "_animals",
        type: "address",
      },
      {
        internalType: "address",
        name: "_supplies",
        type: "address",
      },
      {
        internalType: "address",
        name: "_consumables",
        type: "address",
      },
      {
        internalType: "address",
        name: "_neandersmol",
        type: "address",
      },
      {
        internalType: "address",
        name: "_randomizer",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
    ],
    name: "leaveLaborGround",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "neandersmol",
    outputs: [
      {
        internalType: "contract INeandersmol",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    name: "onERC1155Received",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "result",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pendingOwner",
        type: "address",
      },
    ],
    name: "ownershipHandoverExpiresAt",
    outputs: [
      {
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ownershipHandoverValidFor",
    outputs: [
      {
        internalType: "uint64",
        name: "",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pits",
    outputs: [
      {
        internalType: "contract IPits",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256[]",
        name: "_tokenId",
        type: "uint256[]",
      },
    ],
    name: "removeAnimalsFromLaborGround",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "requestOwnershipHandover",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pits",
        type: "address",
      },
      {
        internalType: "address",
        name: "_animals",
        type: "address",
      },
      {
        internalType: "address",
        name: "_supplies",
        type: "address",
      },
      {
        internalType: "address",
        name: "_consumables",
        type: "address",
      },
      {
        internalType: "address",
        name: "_neandersmol",
        type: "address",
      },
      {
        internalType: "address",
        name: "_randomizer",
        type: "address",
      },
    ],
    name: "setAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "supplies",
    outputs: [
      {
        internalType: "contract IERC1155Upgradeable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class LaborGrounds__factory {
  static readonly abi = _abi;
  static createInterface(): LaborGroundsInterface {
    return new utils.Interface(_abi) as LaborGroundsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LaborGrounds {
    return new Contract(address, _abi, signerOrProvider) as LaborGrounds;
  }
}
